train_dataset: fc100
train_dataset_args: {split: train, augment: resize}
val_dataset: fc100
val_dataset_args: {split: test}
fs_dataset: fc100
fs_dataset_args: {split: test}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: resnet12
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 64}

batch_size: 128
max_epoch: 100
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [90]}

#save_epoch: 5
visualize_datasets: true
